<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  
  <xacro:include filename="$(find quad_flight)/urdf/utils.xacro" />

  <xacro:property name="PI" value="3.1415926535897931"/>

  <xacro:property name="effort_limit" value="0.5" />
  <xacro:property name="velocity_limit" value="0.1" />
  <xacro:property name="damping" value="0.3" />
  <xacro:property name="friction" value="0.1" />
  <xacro:property name="gimbal_yaw_min" value="-30" />
  <xacro:property name="gimbal_yaw_max" value="+30" />
  <xacro:property name="gimbal_pitch_min" value="-30" />
  <xacro:property name="gimbal_pitch_max" value="+30" />

  <xacro:property name="mass_base" value="0.05" />
  <xacro:property name="mass_gimbal_arm" value="0.03" />
  <xacro:property name="mass_gimbal_yaw" value="0.02" />
  <xacro:property name="mass_pad" value="0.005" />
  <xacro:property name="base_width" value=".05" />
  <xacro:property name="base_depth" value=".02" />
  <xacro:property name="base_height" value=".05" />
  <xacro:property name="gimbal_arm_width" value="0.01" />
  <xacro:property name="gimbal_arm_length" value="0.05" />
  <xacro:property name="yaw_joint_width" value="${gimbal_arm_width}" />
  <xacro:property name="yaw_joint_length" value="0.02" />
  <xacro:property name="pad_width" value="0.02" />
  <xacro:property name="pad_height" value="0.02" />
  <xacro:property name="pad_depth" value="0.005" />


  <xacro:property name="mass" value="0.01" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.0" /> <!-- Space btw top of beam and the each joint -->


  <xacro:macro name="camera_gimbal2" params="parent">

    <xacro:include filename="$(find quad_flight)/urdf/materials.xacro" />

<joint name="fixed" type="fixed">
    <parent link="base_link"/>
    <child link="link1"/>
  </joint>

<!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
    <box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
    <box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
      ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="revolute">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
      <limit effort="0" velocity="0" lower="-1" upper="1" />
  </joint>

<link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
    <box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
    <box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
      ixx="${mass / 12.0 * (width*width + height2*height2)}" ixy="0.0" ixz="0.0"
      iyy="${mass / 12.0 * (height2*height2 + width*width)}" iyz="0.0"
      izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

    <gazebo>
      <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/quadrotor</robotNamespace>
        <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
      </plugin>
    </gazebo>

    <gazebo reference="gimbal_base">
      <material>Gazebo/Orange</material>
    </gazebo>

  </xacro:macro>

</robot>
